name: Common Steps

jobs:
  common_steps:
    runs-on: ubuntu-latest
    steps:

      - name: where am i
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR!!"
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "Push!!"
          fi
