name: common_steps
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: where am i
        run: |
          if [ "${{ inputs.env }}" == "pull_request" ]; then
            echo "PR!!"
          elif [ "${{ inputs.env }}" == "push" ]; then
            echo "Push!!"
          fi
