name: prod-env-test

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  push:
    branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:

  pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: prod
    steps:
     - name: git clone the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: configure aws credentials for PR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE}}
          aws-region: ${{ secrets.REGION }}

      - name: Run common steps
        uses: ./.github/workflows/common-steps.yml

  push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
     - name: git clone the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: configure aws credentials for Merge
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_MERGE}}
          aws-region: "eu-central-1"

      - name: Run common steps
        uses: ./.github/workflows/common-steps.yml
